### ISSUE TITLE
load model failed.

### ISSUE THREAD

**Issue by yangze68** [marcobrando/Deep-Skin-Detection-on-Low-Resolution-Grayscale-Images#1]
when run this line : model = load_model(model_filename, custom_objects={'asymmetric_loss': asymmetric_loss})
the Error is:
    for key, item in cls_config.items():
AttributeError: 'list' object has no attribute 'items'
could you please offer the environment on your machine?
the tensorflow, keras version..
thanks

**Comment by marcobrando** [comment]
Thank you for your interest on this project.
I'm able to run "run_model.py" on my ubuntu machine with keras 2.1.4 and tensorflow 1.4.0.

**Comment by yangze68** [comment]
thanks~
